### ISSUE TITLE
I have the same issue if I don't send any body from post man to any service. What is the wrong ?? and how to fix it ??

### ISSUE THREAD

**Issue by SamalaSumanth0262** [expressjs/connect-multiparty#28]
I have the same issue if I don't send any body from post man to any service. What is the wrong ?? and how to fix it ??

_Originally posted by @khataha92 in https://github.com/expressjs/connect-multiparty/issues/22#issuecomment-406753228_

**Comment by dougwilson** [comment]
Hi @SamalaSumanth0262 sorry you're having an issue. In order to help answer any of your questions, you need to provide a complete example application that has the issue and complete step-by-step instructions for how to reproduce the issue. We can help debug through it using a Node.js debugger tool to see where it is going wrong.

**Comment by SamalaSumanth0262** [comment]
Hey @dougwilson , I was in a hurry in the development of my project so I changed the package.
Thank you so much for your quick response.
